import { precacheAndRoute } from 'workbox-precaching';
import { set } from 'idb-keyval';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle the Share Target POST request sent directly from Android OS or OS Sharing
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Check if it exactly matches our share_target action and method
  if (event.request.method === 'POST' && url.pathname === '/add') {
    event.respondWith((async () => {
      try {
        const formData = await event.request.formData();
        const file = formData.get('file');

        if (file) {
          // Safely store the file inside IndexedDB so the React app can pick it up
          await set('shared-image', file);
        }

        // Because we caught an OS level POST, we must return a redirect back to a GET route for React to actually loud.
        return Response.redirect('/add', 303);
      } catch (error) {
        console.error('Error handling share target POST:', error);
        return Response.redirect('/add', 303);
      }
    })());
  }
});
