import { precacheAndRoute } from 'workbox-precaching';
import { set } from 'idb-keyval';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ── Firebase Cloud Messaging (background messages) ────────────────────────────
const firebaseApp = initializeApp({
  apiKey: "AIzaSyDZGovWTi08w_xMk94Dnpvi07DUStynbPw",
  authDomain: "expense-tracker-cdf47.firebaseapp.com",
  projectId: "expense-tracker-cdf47",
  storageBucket: "expense-tracker-cdf47.firebasestorage.app",
  messagingSenderId: "406632111608",
  appId: "1:406632111608:web:398fdb11a47489fb33ca0d",
});

const messaging = getMessaging(firebaseApp);

onBackgroundMessage(messaging, (payload) => {
  console.log('[sw.js] Background message received:', payload);
  const title = payload.notification?.title || 'Expense Tracker';
  const options = {
    body: payload.notification?.body || 'You have a new update.',
    icon: '/app_logo.png',
    badge: '/app_logo.png',
  };
  self.registration.showNotification(title, options);
});

// ── Share Target (Android OS share sheet) ─────────────────────────────────────
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method === 'POST' && url.pathname === '/add') {
    event.respondWith((async () => {
      try {
        const formData = await event.request.formData();
        const file = formData.get('file');
        if (file) {
          await set('shared-image', file);
        }
        return Response.redirect('/add', 303);
      } catch (error) {
        console.error('Error handling share target POST:', error);
        return Response.redirect('/add', 303);
      }
    })());
  }
});
